### ISSUE TITLE
Readme's require migration to markdown

### ISSUE THREAD

**Issue by mgetzbw** [Microsoft/VCSamples#2]
The readme docs are currently in the form of Word flavored HTML, these should be migrated to markdown to display properly on github. Sadly they don't seem to be compatible with an online converter (hence no pull request).

**Comment by ericmitt** [comment]
The file looks already in md format ?
Can you elaborate ?

**Comment by mgetzbw** [comment]
@ericmitt [The ReadMe.htm files IN each sample](https://github.com/Microsoft/VCSamples/blob/master/VC2015Samples/comspy/ReadMe.Htm)

**Comment by ericmitt** [comment]
Oh I see, will do as we migrate the sample to 2015, Thanks

**Comment by ericmitt** [comment]
Working on it...
